### ISSUE TITLE
Create hashtable that you can use in the Kernel

### ISSUE THREAD

**Issue by khazhyk** [novasharper/process_message_passing#1]
hashtab is userspace stuff, can't use it.

uthash we could probably use if we define uthash_malloc as kmalloc, but I want to implemet it ourselves so we can use the slab allocator (we get 3 bonus points for that broski)

**Comment by novasharper** [comment]
Hmm...I guess uthash would work. I would just need to modify my code slightly.

Does it build?

**Comment by khazhyk** [comment]
check reworking branch, I've implemented the hashtable there

**Comment by khazhyk** [comment]
Have you been testing code? I noticed that your makefiles were empty

**Comment by novasharper** [comment]
No, I haven't really been testing the code. For one thing, I haven't written the test programs yet, but also, programming inside a VM is a bit annoying, so I was trying to get the code set up to a basic level first.

**Comment by novasharper** [comment]
For some reason, I keep getting this error: fatal error: string.h: No such file or directory

**Comment by khazhyk** [comment]
You can't use string.h in kernel code

**Comment by khazhyk** [comment]
here, i'm going to merge reworking into master once i finish a few things

**Comment by novasharper** [comment]
Okay.

**Comment by khazhyk** [comment]
Watch out, I force pushed, you might need to reset hard

**Comment by khazhyk** [comment]
Do you use IM or irc?
